version: '3.8'

services:
  str-producer:
    container_name: str-producer
    build:
      context: .
    env_file:
      - "./config/.env"
    ports:
      - "3000:3000"
    networks:
      - str-producer-ntw

networks:
  str-producer-ntw:
    name: str-producer-ntw
    driver: bridge