[tool.poetry]
name = "str-consumer"
version = "0.1.0"
description = ""
authors = ["Max Simões dos Santos <max.santos@tpv-tech.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
